image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build

before_script:
  - ". build/prepare.sh"

build merge request:
  stage: build
  only:
    refs:
      - merge_requests
  artifacts:
    untracked: true
    expire_in: 1 week
  script:
    - "dotnet build -c $FLAVOR $BUILD_ARGS"
    - "dotnet test -c $FLAVOR --no-build"

build:
  stage: build
  only:
    refs:
      - branches
    changes:
      - "src/**/*"
  except:
    refs:
      - merge_requests
  artifacts:
    untracked: true
    expire_in: 1 week
  script:
    - "dotnet build -c $FLAVOR $BUILD_ARGS"
    - "dotnet test -c $FLAVOR --no-build"
    - "dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY"
