image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - publish

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

build and test:
  stage: build
  artifacts:
    paths:
      - TestResults/
      - Packages/
  coverage: '/^\|\s+Total\s+\|\s+\d+\.?\d+%\s+\|\s+(\d+\.?\d+)%\s+\|\s+\d+\.?\d+%\s+\|$/'
  before_script:
    - ". build/prepare.sh"
  script:
    - "dotnet build -c $FLAVOR $BUILD_ARGS"
    - "dotnet test  -c $FLAVOR $TEST_ARGS"
    - "mkdir Packages/ || true"
    - "cp $(find ./ -name *.*nupkg -print) Packages/"

publish nuget packages:
  stage: publish
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_PIPELINE_SOURCE == "web"'
      when: on_success
    - when: never
  script:
    - "printenv"
    - "dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY"
