<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Lucene.Net.Store</RootNamespace>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.*"/>
    <PackageReference Include="coverlet.MTP" Version="10.*"/>

    <PackageReference Include="Lucene.Net.Analysis.Common" Version="4.8.0-beta*"/>
    <PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta*"/>
    <PackageReference Include="Moq" Version="4.*"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Lucene.Net.Store.CachedRemote\Lucene.Net.Store.CachedRemote.csproj"/>
  </ItemGroup>
</Project>
